### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Alexmac22347** [vishnuraghavb/EnRecipes#108]
**Describe the bug**
Latest update on F droid caused all the ingredients and instructions to show as "undefined" and "[object Object]"

**To Reproduce**
1. Open F droid and update the app

**Expected behavior**
My recipes to be unmodified

**Screenshots**
![254293572_395687565590320_2923556781327950016_n](https://user-images.githubusercontent.com/14203288/140867752-ba9e2f07-4883-4824-9898-223d8595d361.png)

**Device information (please complete the following information):**
 - Android Version: 10
 - EnRecipes Version(as in app's about page):  2.0.2

**Additional context**
Worse case I can retype all the info. I was just hoping I don't have to do that (I have about 8 recipes saved right now, I just started using this app recently)

**Comment by vishnuraghavb** [comment]
@Alexmac223 This was a known issue and only occurs on the f-droid release (v2.0.1) because of my mistake, later it was fixed on v2.0.2. In order open the recipes correctly and fix the issue on your end, please install v2.0.2 (if done already, clear app data under settings) and reimport the backup file exported from v2.0.0. Thanks.
