### ISSUE TITLE
Feature Request:   Possibility to import Recipe from URL?

### ISSUE THREAD

**Issue by HyknuF** [vishnuraghavb/EnRecipes#27]
Hi there, thanks for your lovely designed app. works great so far! Would it be possible to add a "import from url" feature? 

For example to automatically add recipes from "chefkoch.de" (for german users) and so on.

I've seen this feature in a nextcloud-recipe app and imo this becomes very handy.

Thanks in advance!

Cheers

**Comment by vishnuraghavb** [comment]
Hello, Thanks for using EnRecipes!
Your requested feature is already on the [roadmap](https://github.com/vishnuraghavb/EnRecipes/projects/1#card-51118529) and it'll be implemented in a later stage.
Keep supporting!

**Comment by HyknuF** [comment]
Nice, thanks in advance!

**Comment by Moini** [comment]
Would be cool if it also had an offline import of the standardized xml recipe format (this is all I'd really need).

**Comment by vishnuraghavb** [comment]
@Moini As far as I know, there is no standard xml recipe format. Each app exports with its own conventions. So it is quite difficult to implement such feature IMO.

Also, It would be really helpful for me to understand, if you could share a sample recipe exported in the above said format.

**Comment by Moini** [comment]
@vishnuraghavb  Oh, there is! I believe that's what Chefkoch.de (and many other websites) use, actually.

You can find many standardized xml metadata formats at schema.org. For recipes, it's https://schema.org/Recipe .

**Comment by vishnuraghavb** [comment]
@Moini Sorry I thought it was something that is exported by an app. Actually I know about schema.org recipe format and already have added it to the [roadmap](https://github.com/vishnuraghavb/EnRecipes/projects/1#card-51118529) long back. Since this feature requires network permissions, I've planned it for later.

Thanks for your idea of offline xml import though. If it is totally offline then, I would have no problem implementing the feature.
I'm adding it to the roadmap for now.

**Comment by Moini** [comment]
Thank you, @vishnuraghavb - that's cool! I think the nextcloud apps that I'm currently using, for example, also build upon this format. They don't work too well for me - at least the mobile version doesn't.
